**Import the NumPy library to use its pre existing functions**

In [3]:
import numpy as np

**Create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
ndarray as X_normalized.npy**

In [5]:
#Create a 5 x 5 array that will generate random values as its elements
X = np.random.rand(5, 5)

In [6]:
#Use the formula stated in the problem sheet to setup the logic

#use np.mean() to get the mean of X andd np.std() for the standard deviation
Y = np.mean(X)
Z = np.std(X)

In [7]:
#Setup the equation

Normalized = (X - Y) / Z
Normalized

array([[ 0.5526046 ,  0.12726316, -0.80001875,  1.06229414,  0.78735574],
       [ 0.56284122,  0.67926844,  1.35676258,  1.47395034,  0.36965874],
       [-1.23921927,  1.73569177, -0.72257318,  1.4522174 , -0.78393103],
       [-1.3031662 , -0.55957444, -0.5892481 , -0.52887628, -1.12697151],
       [-1.09974771, -1.51764196,  1.22593217, -0.66356238, -0.45130949]])

In [8]:
#Save the normalized ndarray using the np.save function
np.save('X_normalized.npy', Normalized)

**Create a 10 x 10 ndarray, containing the square of the square of the first 100 integers**

In [10]:
#Create an array of the square of the first 100 integers
X = np.arange(1, 101) ** 2
X

array([    1,     4,     9,    16,    25,    36,    49,    64,    81,
         100,   121,   144,   169,   196,   225,   256,   289,   324,
         361,   400,   441,   484,   529,   576,   625,   676,   729,
         784,   841,   900,   961,  1024,  1089,  1156,  1225,  1296,
        1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,  2025,
        2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,  2916,
        3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,  3969,
        4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,  5184,
        5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,  6561,
        6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,  8100,
        8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
       10000])

In [11]:
#Reshape the array into a 10 x 10
X = X.reshape(10, 10)
X

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [12]:
#Use the module operator to set up a logic and determine which elements are divisible by 3
divisible = X[X % 3 == 0]
divisible

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [13]:
#Save the ndarray into 'div_by_3.npy'
np.save('div_by_3.npy', divisible)